### ISSUE TITLE
optimization

### ISSUE THREAD

**Issue by YChen-1998** [grepthat/libOpenDRIVE#11]
I'm sorry to bother you again. I try to fit this road like number 8 with Bezier curve, but I find that my result is wavy line. Do I want to know what optimization method is available，thank you very much

**Comment by YChen-1998** [comment]
OK, I only drew a route
![Screenshot from 2021-11-30 13-53-17](https://user-images.githubusercontent.com/82098989/143994346-03041a58-4730-4ec8-9226-1262f1aadaad.png)
[sv.txt](https://github.com/grepthat/libOpenDRIVE/files/7623325/sv.txt)

**Comment by grepthat** [comment]
I would trust the ODR Viewer as reference. I can't really tell you why you are getting this. I just noticed that your poly3 segments are really short. Maybe try creating longer segments.
