### ISSUE TITLE
traffic rule and routing

### ISSUE THREAD

**Issue by Rogers0701** [grepthat/libOpenDRIVE#15]
Hello，I am very interested in your project and I benefit a lot.Do you have any plans about adding association between  opendrive map elements and related traffic rules or utilizing map data to generate a routing map?

**Comment by Rogers0701** [comment]
and I don't understand the function of 'center_map' and cnt.would you tell me some explanations?Thanks a lot.

**Comment by grepthat** [comment]
'center_map' puts the center of the map at (0,0). This is because some xodr maps use ECEF coordinates which are in the range of 10e+6. Due to floating point precisions this results in "wobbly" maps if the coordinates are not adjusted. But it's optional anyway.

**Comment by Rogers0701** [comment]
Appreciate it！
