### ISSUE TITLE
RoadLink is empty 

### ISSUE THREAD

**Issue by aifei7320** [grepthat/libOpenDRIVE#16]
In my using case, i want to use link information, but it's all empty, but i checked xodr file, there is link node and has value for each key.Then i try to print it's value, but i got empty. After i check other node,  you using attribute function to extract it's value, then it appeared.
![image](https://user-images.githubusercontent.com/24615852/147725657-57fd9db2-a49f-4ee6-91cf-40e38c73e456.png)
![image](https://user-images.githubusercontent.com/24615852/147726277-b7c45fed-a51d-4b22-a35e-580bcc7e3826.png)

**Comment by grepthat** [comment]
You are right. Those should be attributes, not children.
