### ISSUE TITLE
Add version tag(s)

### ISSUE THREAD

**Issue by johschmitz** [grepthat/libOpenDRIVE#17]
Awesome library! Once you are ready for the first release could you please add version Git tags? Preferably using semver 2.0 (https://semver.org/)

**Comment by grepthat** [comment]
Good point! I have not been very thorough with documentation or versioning. I'll follow the semver 2.0 versioning. I added the tag 0.1.0. I'll add tag 1.0.0 once I implemented roadsigns and all major elements of the OpenDrive are parsed.

**Comment by johschmitz** [comment]
That's good, you can continue to numbers like 0.18.0 and keep increasing in small steps until you feel you are ready for 1.0.0 🙂

**Comment by grepthat** [comment]
I started using tag. I'm not strictly applying semver though since I'm still changing the API in a non-backward-compatible way and I don't want to increase the major version all the time. I'm planing on applying to the semver version scheme when reaching v1.0.
