### ISSUE TITLE
Lost laneOffset attribute

### ISSUE THREAD

**Issue by aifei7320** [grepthat/libOpenDRIVE#18]
In Opendrive there is an attribute called laneOffset, it is not included in this library. It's an attribute of lanesection.
![image](https://user-images.githubusercontent.com/24615852/148006523-5be201b5-ae50-4a15-8aa8-224d3acb2e14.png)

**Comment by grepthat** [comment]
It's included and used. It's parsed in _OpenDriveMap.cpp_ and immediately applied to the `Lane::outer_border` and `Lane::inner_border`. 

https://github.com/grepthat/libOpenDRIVE/blob/f4cfa3bd978a9c0065370658644b9858dfbf5543/src/OpenDriveMap.cpp#L251-L252

https://github.com/grepthat/libOpenDRIVE/blob/f4cfa3bd978a9c0065370658644b9858dfbf5543/src/OpenDriveMap.cpp#L445-L449
