### ISSUE TITLE
implement signal parsing

### ISSUE THREAD

**Issue by CoderChen01** [grepthat/libOpenDRIVE#21]
Hello author, thank you very much for open source such a powerful library, I think it fills the gap of opendrive official does not provide parsing library.
I find that the signal element of opendrive may represent the signal element differently. Is that why you didn't parse signal?

**Comment by grepthat** [comment]
Thanks! Appreciate it. I simply didn't have time so far to implement signal parsing. It's the next thing on my list though.

**Comment by hee0624** [comment]
we also need to parse signal. e.t.  traffic_light

**Comment by LevieSun** [comment]
I found that "signals" can be parsed on "odrviewer.io", Is there any related open source code？

**Comment by grepthat** [comment]
I haven't had the time yet to add signals. I also don't parse them on https://odrviewer.io yet. Maybe you are mistaking `road::objects` for signals? Those are being parsed.

**Comment by hahne** [comment]
Hi,

I have implemented the parsing of the signals. Is there any interest in creating a pull request for that?
