### ISSUE TITLE
Rotation in odrviewer.io not possible, zoom mousewheel direction inconsistent

### ISSUE THREAD

**Issue by johschmitz** [grepthat/libOpenDRIVE#24]
I noticed that the it is not possible to rotate the view in https://odrviewer.io/ like it is in https://sebastian-pagel.net/odrviewer/

Also the direction of the mouse wheel zoom is inconsistent (between https://odrviewer.io/ and https://sebastian-pagel.net/odrviewer/).
I recommend you to use the same direction as https://www.google.com/maps/ does (also Blender and many other tools), since most of the people are used to that:
- Mousewheel up -> Zoom in
- Mousewheel down -> Zoom out

**Comment by grepthat** [comment]
I agree with the zoom direction. I updated that to zoom out on mouse wheel down. About the rotation: Is it not possible at all for you to rotate or is the rotation behaviour different from  https://sebastian-pagel.net/odrviewer/ ? Which platform and controls (touch or mouse) are you using?

**Comment by johschmitz** [comment]
It was not possible for me to rotate at all. Is it supposed to be on right mouse button or maybe middle mouse? I think I was using Firefox on Linux. But I guess it would make sense to test the most common browsers like Chrome, Firefox, Safari, Edge on Windows, Linux, Mac, iOS and Android.

**Comment by grepthat** [comment]
I tested it on Ubuntu 18.04 with Firefox 98.0.2 and Chrome 91.0.4472 as well as on MacOS Safari 15.4 and Firefox 98.0.2 and had no issues.

 Are you pressing the pressing the **Shift** key while dragging the mouse to rotate?

**Comment by johschmitz** [comment]
I see, pressing shift does work indeed. I find that super non-intuitive though. Most 3D applications have rotation directly on one of the mouse 3 buttons, including https://sebastian-pagel.net/odrviewer/
So I would prefer that.

**Comment by grepthat** [comment]
Thanks for pointing out the rotation on right mouse button. I added that now. So the behaviour should be like https://sebastian-pagel.net/odrviewer/. I still want to keep PAN on the left mouse button as I feel it's used more frequently than rotation for navigating maps.

**Comment by johschmitz** [comment]
Nice. I am okay with you deciding which mouse button does what, that is not consistent between most 3D applications anyway..
What would be cool would be an additional 3D ego shooter like flight mode.
