### ISSUE TITLE
Viewer interface in old version

### ISSUE THREAD

**Issue by flok** [grepthat/libOpenDRIVE#29]
I happened to notice that the Viewer still looks like the old viewer from some months ago and not like the current one available at [https://odrviewer.io/](https://odrviewer.io/). Is there any plans to release the code for that as well and replace the current Viewer with it?

**Comment by grepthat** [comment]
https://odrviewer.io is somewhat a work in progress. It uses this library but the viewer code isn't open-source. Currently I don't have any plans on releasing the viewer code. Overall I'm planing to focus this project more on the library part and maybe make a separate project for the viewer.
