### ISSUE TITLE
Scroll to zoom direction inconsistent

### ISSUE THREAD

**Issue by johschmitz** [grepthat/libOpenDRIVE#32]
Scroll to zoom direction between https://odrviewer.io/ and https://sebastian-pagel.net/odrviewer/index.html is inconsistent.
Can you make it as in Google Maps to make it intuitive for both apps:
Scroll up to zoom in and scroll down to zoom out

**Comment by grepthat** [comment]
You're right. Thanks for pointing it out. Should be fixed now.
