### ISSUE TITLE
about obj file

### ISSUE THREAD

**Issue by IKMUN95** [grepthat/libOpenDRIVE#34]
Hi I'm trying to import obj file (exported from odrviewer) to Unreal Engine4. 
When I import obj file, It shows shape of the road but I can't see any roadmarks, lane, reference line, and etc.  
Am I missing any procedure or  is this feature not supported originally?
I will be glad to receive any recommendations to help solving this problem.

![image](https://user-images.githubusercontent.com/81611790/168046493-1f1278d5-2d5b-4f93-880d-d7fa51b40076.png)

**Comment by grepthat** [comment]
The roadmark meshes should be included in the generated .obj but they don't have any special texture to highlight them in the mesh. If you switch to wireframe view you should be able to make out road marks. The .obj export from odrviewer.io is very basic (does not include textures, produces a single big mesh) and will simply call `odr::get_road_network_mesh(odr_map, _eps);` (from _Viewer/ViewerUtils.h_). 

I have it on my list to improve this but if you want finer control on the mesh generation I would recommend using this lib to write a .obj export that fits your needs.
