### ISSUE TITLE
how to draw objects in js?

### ISSUE THREAD

**Issue by zibiaowu** [grepthat/libOpenDRIVE#38]
I see that there is parsing objects record in the c++ code, but I don't know how to draw with these data, can you please provide an example in the viewer or briefly describe how to use the `road_objects_mesh` data? 

Thanks!

**Comment by grepthat** [comment]
The `RoadObjectsMesh` also inherits from `Mesh3D`. So it has a `vertices` and `indices` member. This should be sufficient to create a mesh. Three subsequent indices describe a triangle in the mesh. There are already utility functions in _main.js_ to create a mesh from this. The pattern to create the road objects mesh should be the same as for the roadmarks mesh:

```js
    /* roadmarks geometry */
    const odr_roadmarks_mesh = odr_road_network_mesh.roadmarks_mesh;
    const roadmarks_geom = get_geometry(odr_roadmarks_mesh);

    /* roadmarks mesh */
    roadmarks_mesh = new THREE.Mesh(roadmarks_geom, roadmarks_material);
    scene.add(roadmarks_mesh);
```
