### ISSUE TITLE
Lane.cpp get_roadmarks() function may not return the correct roadmarks between the start and end range.

### ISSUE THREAD

**Issue by sanjodev** [grepthat/libOpenDRIVE#39]
In Lane.cpp, the function:

`std::vector<RoadMark> Lane::get_roadmarks(double s_start, double s_end) const`

I think there might be a bug in the comparison code for getting the upper_bound iterator as it currently is:

`
[](const double& s, const RoadMarkGroup& rmg) -> bool { return (rmg.lanesection_s0 + rmg.s_offset) < s; });
`

I think the comparison function for upper_bound should instead be: 

`
[](const double& s, const RoadMarkGroup& rmg) -> bool { return s < (rmg.lanesection_s0 + rmg.s_offset); });
`

According to: https://en.cppreference.com/w/cpp/algorithm/upper_bound

The 1st argument 's' should compare less than the 2nd argument 'rmg'.

The comparison function for lower_bound later in the function is correct because 's' is the 2nd argument in that case.

**Comment by grepthat** [comment]
You're right! Thanks for finding this and the detailed description. 

I'm surprised that this did not cause more trouble. I think with this error the iterator from `std::upper_bound` always pointed to the last `roadmark_groups` entry. Just superficially looking at this, it seems like only always one rmg would be evaluated. Feel free to add more info on this if you have more insights on the effects of this error.
