### ISSUE TITLE
Mouse posion does not response correctly

### ISSUE THREAD

**Issue by aifei7320** [grepthat/libOpenDRIVE#4]
Firstly, this is a really nice project.
There is a issue , i can not pick the road with my mouse point over the road, there is an offset between mouse and road.

**Comment by grepthat** [comment]
I thought I fixed that one. Which browser are you using? Can you post a screenshot showing the issue?

**Comment by aifei7320** [comment]
I am using chrome, ok later i will post a screenshot.

**Comment by cxruan** [comment]
https://github.com/grepthat/libOpenDRIVE/blob/b5fea86f206e8e3cabe51ac8189ffbda6803d12a/Viewer/main.js#L339
I also met this problem. In my case, replacing the above line with:
```javascript
camera.setViewOffset(renderer.getContext().drawingBufferWidth, renderer.getContext().drawingBufferHeight, mouse.x * renderer.getPixelRatio() | 0, mouse.y * renderer.getPixelRatio() | 0, 1, 1);

```
fixed my problem.

**Comment by cxruan** [comment]
> @cxruan seems to work 👍 If you want you can create a PR

Sure. The PR is created.

**Comment by grepthat** [comment]
fixed by https://github.com/grepthat/libOpenDRIVE/pull/10
