### ISSUE TITLE
OSM/Lanelet export

### ISSUE THREAD

**Issue by jonny-sexton** [grepthat/libOpenDRIVE#40]
One feature that could be quite nice would be to export the map to various different file formats, such as lanelet2, osm, rd5, etc.

**Comment by yonhdee** [comment]
see this https://commonroad.in.tum.de/tools/scenario-designer, you can import `.xodr` and export `.osm` / lanelet2 using the panel, and it's open-source

**Comment by jonny-sexton** [comment]
will check it out, thank you!
