### ISSUE TITLE
Is odrviewer.io opensourced?

### ISSUE THREAD

**Issue by mljack** [grepthat/libOpenDRIVE#41]
Hi, do you know whether the web site [odrviewer.io](https://odrviewer.io/) is opensource or not?
Thanks!

**Comment by grepthat** [comment]
Hi mljack,
sry odrviewer.io is not open source. It uses this library though for all xodr related functions.

**Comment by PigKnight-coder** [comment]
>Hi grepthat,

odrviewer.io is a wonderful product, it is much better than [viewer online].
I'd like to build my scenario editor with it. How can I get it?

**Comment by rpf1019** [comment]
that's exactly what I want, too
