### ISSUE TITLE
cannot compile

### ISSUE THREAD

**Issue by sibi-venti** [grepthat/libOpenDRIVE#44]
![image](https://user-images.githubusercontent.com/85477641/192986601-b4162874-f565-460d-871a-528efdb18b4c.png)

**Comment by grepthat** [comment]
Thanks for pointing this out. It seems to be a problem with GCC. Should be fixed now.

https://stackoverflow.com/questions/2282349/specialization-of-templateclass-tp-struct-stdless-in-different-namespace
