### ISSUE TITLE
Ref Line .cpp bad definition cannot compile 

### ISSUE THREAD

**Issue by the-genco-ibis** [grepthat/libOpenDRIVE#45]
![image](https://user-images.githubusercontent.com/77912970/193439340-77736220-8b45-487c-ad51-0c4d5166d669.png)
![image](https://user-images.githubusercontent.com/77912970/193439357-e6499638-022b-4810-a8c7-bc4bdd559b02.png)

**Comment by grepthat** [comment]
Please post more details about your build system (OS, compiler version, ...). I can't reproduce this on ubuntu 18.04 or 20.04.

**Comment by grepthat** [comment]
closed due to inactivity
