### ISSUE TITLE
Ubuntu 20.04, make error when compiling the build step in README

### ISSUE THREAD

**Issue by Merealtea** [grepthat/libOpenDRIVE#53]
I met the same problem slightly like this one [https://github.com/grepthat/libOpenDRIVE/issues/49](url), and I also change the [libOpenDRIVE/CMakeLists.txt](https://github.com/grepthat/libOpenDRIVE/blob/39755b36e4b8f6aa4129c72525701f5288d4991a/CMakeLists.txt#L58) as it suggested. But I still got the error below:
![1669347814748](https://user-images.githubusercontent.com/67770232/203897110-99269022-8608-4ee6-ac92-2dd88ad243a5.png)

my gcc version is 9.4.0 (Ubuntu 9.4.0-1ubuntu1~20.04.1)

**Comment by grepthat** [comment]
should be fixed with https://github.com/grepthat/libOpenDRIVE/pull/52, feel free to reopen if it's still broken
