### ISSUE TITLE
RefLine::match gives wrong result

### ISSUE THREAD

**Issue by XiaXingLuo** [grepthat/libOpenDRIVE#54]
I use the code following:
double s = odr_ref.match(destPoint[0], destPoint[1])
I want to use the destPoint to get the s，but the result of s isn't matched the real map, so can you offer some refference or the functions of the function.

**Comment by grepthat** [comment]
Can you provide an the Opendrive file you are using and a complete code example?

**Comment by XiaXingLuo** [comment]
Ok, Thanks for your replay.
Test point(x,y) is :
constodr::Vec2DdestPoint = { 7435.542, -2918.713 };
I use VTD open the opendrive data and getsome information that the point is located in Road "128" and s  approximate coordinates is 20.(Tomorrow I will give you specific value of s)
I want to use the function of  "match " to get the point's s coordinates. The code is following.
odr::Roadodr_road = odr_map.id_to_road.at(destRoadID);
odr::RefLineodr_ref = odr_road.ref_line;
doubles = odr_ref.match(destPoint[0], destPoint[1]);
The result of the code is 0.004. If I missunderstand the function of match, please forgive me.
------------------------------------------------------------------------------------------------------------------------------------------
In the end, I have another prolem if you can offer help I will appreciate.
I just start to learn opendrive. I have one point in world coordinates system, I want to use the coordinates information to loacte the point in opendrive map, where is the point located in? 
Firstly,  I need the RoadID, then get the s coordinates of the point, finally, How can I know the information of Lansection and LaneID the point loated in. 
Now, T get the RoadID in VTD, I have problems in calculating the s coordinate and getting LaneID.




At 2023-01-29 20:11:51, "Sebastian Pagel" ***@***.***> wrote:

Can you provide an the Opendrive file you are using and a complete code example?

**Comment by XiaXingLuo** [comment]
Ok, Thanks for your replay.
Test point(x,y) is :
constodr::Vec2DdestPoint = { 7435.542, -2918.713 };
I use VTD open the opendrive data and getsome information that the point is located in Road "128" and s  approximate coordinates is 20.(Tomorrow I will give you specific value of s)
I want to use the function of  "match " to get the point's s coordinates. The code is following.
odr::Roadodr_road = odr_map.id_to_road.at(destRoadID);
odr::RefLineodr_ref = odr_road.ref_line;
doubles = odr_ref.match(destPoint[0], destPoint[1]);
The result of the code is 0.004. If I missunderstand the function of match, please forgive me.
------------------------------------------------------------------------------------------------------------------------------------------
In the end, I have another problem if you can offer help I will appreciate.
I just start to learn opendrive. I have one point in world coordinates system, I want to use the coordinates information to loacte the point in opendrive map, where is the point located in? 
Firstly,  I need the RoadID, then get the s coordinates of the point, finally, How can I know the information of Lansection and LaneID the point loated in. 
Now, T get the RoadID in VTD, I have problems in calculating the s coordinate and getting LaneID.




At 2023-01-29 20:11:51, "Sebastian Pagel" ***@***.***> wrote:

Can you provide an the Opendrive file you are using and a complete code example?

**Comment by grepthat** [comment]
Please provide the Opendrive file for it

**Comment by XiaXingLuo** [comment]
Sorroy, I send the wrong data. The new data is Opendrive data. The picture shows some infrmation of the point.Coordinates of s is about 6.







At 2023-01-29 22:05:12, "Sebastian Pagel" ***@***.***> wrote:

Please provide the Opendrive file for it

**Comment by XiaXingLuo** [comment]
![image](https://user-images.githubusercontent.com/62875177/215375098-95199059-e053-4161-aa63-55b25733a478.png)

**Comment by XiaXingLuo** [comment]
Thanks, The code have no problem. I find that the map have coordinates offset, I forget to use the offset when inputing the test point. Now, I can use the absolute s coordinates to locate where lanesection the point is and get the coordinates of s in the reference lane, I have two points P_test(x,y)、P_s(x,y), I decide to use Δy and relative information of angle to get the coordinates of t, finally I can use the code "LaneSection::get_lane_id(const double s, const double t) const" , does this idea work.

**Comment by grepthat** [comment]
Good point. I didn't think about the offsets. You can also set `center_map = false` in the `OpenDriveMapConfig` options when loading the map. This means no offset is applied.

**Comment by Damonyhk** [comment]
> Thanks, The code have no problem. I find that the map have coordinates offset, I forget to use the offset when inputing the test point. Now, I can use the absolute s coordinates to locate where lanesection the point is and get the coordinates of s in the reference lane, I have two points P_test(x,y)、P_s(x,y), I decide to use Δy and relative information of angle to get the coordinates of t, finally I can use the code "LaneSection::get_lane_id(const double s, const double t) const" , does this idea work.

@XiaXingLuo 您好，能请教一下您吗？地图有坐标偏移是什么意思呢？我的xodr文件里面并没有偏移，但是match接股票仍然不对。
![image](https://github.com/user-attachments/assets/f0a15aee-94a8-4b42-9f52-1772d2e0e0cc)

**Comment by XiaXingLuo** [comment]
> > Thanks, The code have no problem. I find that the map have coordinates offset, I forget to use the offset when inputing the test point. Now, I can use the absolute s coordinates to locate where lanesection the point is and get the coordinates of s in the reference lane, I have two points P_test(x,y)、P_s(x,y), I decide to use Δy and relative information of angle to get the coordinates of t, finally I can use the code "LaneSection::get_lane_id(const double s, const double t) const" , does this idea work.
> 
> @XiaXingLuo 您好，能请教一下您吗？地图有坐标偏移是什么意思呢？我的xodr文件里面并没有偏移，但是match接股票仍然不对。 ![image](https://private-user-images.githubusercontent.com/62838254/358116782-f0a15aee-94a8-4b42-9f52-1772d2e0e0cc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQwMjkyODgsIm5iZiI6MTcyNDAyODk4OCwicGF0aCI6Ii82MjgzODI1NC8zNTgxMTY3ODItZjBhMTVhZWUtOTRhOC00YjQyLTlmNTItMTc3MmQyZTBlMGNjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE5VDAwNTYyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY5NGZiMjQyZGEyOTRhZTYxNzRhY2RhMjFjZDA3N2IwYTJmMTBlN2EyOTljNTRmMGQxM2Q3YzZiN2MzYjYxNDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.azrf9gk1ZJOOi06hoXtSREGprXUez8NMjkZ8ieenueU)

一般采的地图数据，都是经过偏移处理的。不然实际坐标几千几万，不便于计算。这个偏移可以理解为数学上的中心化，让坐标值变小。源码不知道后来修改了没，如果不设置代码自动会对地图坐标数据进行中心化，自己看源码。你在测试时，要保持输入的点数据坐标和地图坐标数量级上一致，才能得到正确的结果。

**Comment by Damonyhk** [comment]
> > > Thanks, The code have no problem. I find that the map have coordinates offset, I forget to use the offset when inputing the test point. Now, I can use the absolute s coordinates to locate where lanesection the point is and get the coordinates of s in the reference lane, I have two points P_test(x,y)、P_s(x,y), I decide to use Δy and relative information of angle to get the coordinates of t, finally I can use the code "LaneSection::get_lane_id(const double s, const double t) const" , does this idea work.
> > 
> > 
> > @XiaXingLuo 您好，能请教一下您吗？地图有坐标偏移是什么意思呢？我的xodr文件里面并没有偏移，但是match接股票仍然不对。 ![image](https://private-user-images.githubusercontent.com/62838254/358116782-f0a15aee-94a8-4b42-9f52-1772d2e0e0cc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQwMjkyODgsIm5iZiI6MTcyNDAyODk4OCwicGF0aCI6Ii82MjgzODI1NC8zNTgxMTY3ODItZjBhMTVhZWUtOTRhOC00YjQyLTlmNTItMTc3MmQyZTBlMGNjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE5VDAwNTYyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY5NGZiMjQyZGEyOTRhZTYxNzRhY2RhMjFjZDA3N2IwYTJmMTBlN2EyOTljNTRmMGQxM2Q3YzZiN2MzYjYxNDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.azrf9gk1ZJOOi06hoXtSREGprXUez8NMjkZ8ieenueU)
> 
> 一般采的地图数据，都是经过偏移处理的。不然实际坐标几千几万，不便于计算。这个偏移可以理解为数学上的中心化，让坐标值变小。源码不知道后来修改了没，如果不设置代码自动会对地图坐标数据进行中心化，自己看源码。你在测试时，要保持输入的点数据坐标和地图坐标数量级上一致，才能得到正确的结果。

非常感谢，不过我的现在的代码里面中心化默认false。match有0.0x的偏移是因为使用了非精准的匹配算法golden_search。
