### ISSUE TITLE
get_xyz() returns wrong coordinates

### ISSUE THREAD

**Issue by Jmingyu0822** [grepthat/libOpenDRIVE#58]
I use 'get_xyz' function but the result coordinate is different from coordinate in 'https://sebastian-pagel.net/odrviewer/' .

How can i get world coordinate without error?

**Comment by grepthat** [comment]
By default when loading the map it gets centered. To get the right world coordinate point you probably have to add `OpenDriveMap::x_offs` and `y_offs`.

**Comment by grepthat** [comment]
closed due to inactivity
