### ISSUE TITLE
noticed you had removed Webassembly，may i ask the reason of that，

### ISSUE THREAD

**Issue by chaomingd** [grepthat/libOpenDRIVE#61]

**Comment by grepthat** [comment]
I want to focus more on the library and less on maintaining the JavaScript bindings. They were just means for the purpose of powering the first version of the viewer. I'd rather encourage others to create the bindings like the [imgui-js](https://github.com/flyover/imgui-js ) project does it for [imgui](https://github.com/ocornut/imgui).
