### ISSUE TITLE
road mesh created from arc and line geometry faulty

### ISSUE THREAD

**Issue by chaomingd** [grepthat/libOpenDRIVE#62]
![image](https://user-images.githubusercontent.com/31772762/222308699-cced43f5-0991-4641-9593-891789bbd97b.png)
![image](https://user-images.githubusercontent.com/31772762/222308875-8cf9e4ed-f5c6-4b57-877d-69a331b6348a.png)

**Comment by grepthat** [comment]
please also provide the .xodr file for this

**Comment by chaomingd** [comment]
Thank you for your reply. Here is the file

[demo.xml.zip](https://github.com/grepthat/libOpenDRIVE/files/10893552/demo.xml.zip)

**Comment by grepthat** [comment]
Thanks for providing the file! https://github.com/grepthat/libOpenDRIVE/commit/430ecbcd82d45bd615742580be9702cd70691e88 should fix this. It should also be fixed for [odrviewer.io](https://odrviewer.io). Please check.

It's a bug that has been there some time. This might have quite a big impact on the parsing.

**Comment by chaomingd** [comment]
that's great，thank you for resolved this bug，it's very useful。
