### ISSUE TITLE
get .obj file from the code 

### ISSUE THREAD

**Issue by Jmingyu0822** [grepthat/libOpenDRIVE#63]
1. I want to get .obj file from the code How Could i get it..?!

2. In web site (https://odrviewer.io/), if i push 'export .obj' button, the screen become black like under picture.
    How could i use the function? please explain the function, thank you.
![image](https://user-images.githubusercontent.com/88613557/225827961-a510dcc3-ac33-40f0-a6bf-0b4c6b99348d.png)
![image](https://user-images.githubusercontent.com/88613557/225829765-8bc7d345-b774-455a-8116-f6cf769428aa.png)

**Comment by grepthat** [comment]
Thanks for noticing! It should be fixed now.

**Comment by grepthat** [comment]
I re-added the functionality of getting a road network mesh in commit https://github.com/grepthat/libOpenDRIVE/commit/74a5d0760ff933830750d931325eaeb7a6b9e371 This was accidentally  removed when deprecating the viewer. You can now get an .obj like this via code:

```c++
odr::OpenDriveMap odr_map("test.xodr");
odr::RoadNetworkMesh road_network_mesh = odr_map.get_road_network_mesh(0.1 /*eps*/);
std::ofstream out_file("out.obj");
out_file << road_network_mesh.get_mesh().get_obj() << std::endl;
out_file.close();
```

**Comment by Jmingyu0822** [comment]
Thank you for your help @grepthat
But, I couldn't get some more information such as middle line, junction, etc.. in obj picture(3D Viewer).

![image](https://user-images.githubusercontent.com/88613557/226245188-789137c3-78e1-4738-9469-aef5cfe279bd.png)

Could i get more information from the code?

**Comment by grepthat** [comment]
Do you mean the junction areas are missing in the generated .obj file? 

Best provide an example .xodr
