### ISSUE TITLE
Wasm help

### ISSUE THREAD

**Issue by Maximilian-v-H** [grepthat/libOpenDRIVE#67]
I read your README, which specifies that you have left WASM behind.

I wanted to ask if it would be possible for you to give me a short introduction to what you have done in v0.3.0 with WASM, so that I can extend that myself.

A few resources how to best get into it would be sufficient enough.

Thank you in advance

**Comment by grepthat** [comment]
Hi Maximilian, 
thanks for your interest in the project. Keeping the WASM bindings up-tp-date meant maintaining [Embind.cpp](https://github.com/grepthat/libOpenDRIVE/blob/0.3.0/src/Embind.cpp) when the function declarations change. The [documentation](https://emscripten.org/docs/porting/connecting_cpp_and_javascript/embind.html) of Embind is pretty good. I used Emscripten to generate WebAssembly but there are also other options. There is some info on how to build with Emscripten [here](https://emscripten.org/docs/compiling/Building-Projects.html#)

**Comment by Maximilian-v-H** [comment]
Hi,

Thanks for the reply!

This already helps a lot, will look into the resources and try my best!

Will keep you up to date if you want (I will create a fork of the project).
