### ISSUE TITLE
ParamPoly3 ：need help

### ISSUE THREAD

**Issue by qqkkwan** [grepthat/libOpenDRIVE#7]
First ,It's a great project. I am doing something like converting some data to opendrive files，but i met some problems by converting to ParamPoly3 geometry . I think maybe I will be inspired by this project，but i really don't understand how to build ParamPoly3 after i read the code. Could you please give me some explanations ? Thanks a lot~

**Comment by grepthat** [comment]
Thanks! I appreciate it. So the **ParamPoly3** is actually a [Cubic Bézier curve](https://en.wikipedia.org/wiki/B%C3%A9zier_curve#Cubic_B%C3%A9zier_curves), which is a more common representation. For the Cubic Bézier curve there are four control points determining how the curve looks like. There are examples like [this](https://www.desmos.com/calculator/d1ofwre0fr) online where you can play around with the control points.

In [ParamPoly3.cpp](https://github.com/grepthat/libOpenDRIVE/blob/ef07612081119ce6117d171fe3f6d94b25f865e0/Geometries/ParamPoly3.cpp#L40) I'm actually getting the control points from the **ParamPoly3 parameters** (aU, bU,...). To get the control points for a ParamPoly3 the equations are (implemented in [CubicBezier.hpp](https://github.com/grepthat/libOpenDRIVE/blob/ef07612081119ce6117d171fe3f6d94b25f865e0/CubicBezier.hpp#L27-L48) in a more generic way):

```
p0 = (aU | aV)
p1 = (bu/3 + p0x | bV/3 + p0y)
p2 = (cU/3 + 2*p1x - p0x  | cV/3 + 2*p1y - p0y)
p3 = (dU + 3*p2x - 3*p1x + p0x | dV + 3*p2y - 3*p1y + p0y)
```

The inverse of that (from control points to ParamPoly3 coefficients) is implemented [here](https://github.com/grepthat/libOpenDRIVE/blob/ef07612081119ce6117d171fe3f6d94b25f865e0/CubicBezier.hpp#L50-L70). 

So you could fit a Cubic Bézier curve through your data, get the coefficients of it and write that to the .xodr file.

**Comment by qqkkwan** [comment]
good ! thanks a lot!

**Comment by YChen-1998** [comment]
Thanks! I appreciate it.I want to know how to calculate the equation of finding ParamPoly3 parameters at known control points，Thanks a lot~

**Comment by grepthat** [comment]
For converting the control points to ParamPoly3 parameters I used [this](https://en.wikipedia.org/wiki/B%C3%A9zier_curve#Polynomial_form) equation. It's implemented [here](https://github.com/grepthat/libOpenDRIVE/blob/ef07612081119ce6117d171fe3f6d94b25f865e0/CubicBezier.hpp#L50-L70)

![image](https://user-images.githubusercontent.com/42587026/143292583-98600842-25c5-4494-bf6e-8a8da71b7a2a.png)

Resolving that equation for a cubic Bezier should result in:
```
C0 = P0
C1 = 3*P1 - 3P0
C2 = 3*P2 - 6*P1 + 3P0
C3 = P3 - 3*P2 + 3*P1 - P=
```
