### ISSUE TITLE
疑惑

### ISSUE THREAD

**Issue by XiaoLiuH** [grepthat/libOpenDRIVE#72]
我想将这个功能集成到我的一个管理系统中，但是我没弄明白，所以想请问一下就是咱们这个项目和前端怎么连接呢？

**Comment by grepthat** [comment]
Please report issues in English

**Comment by XiaoLiuH** [comment]
I want to integrate this function into one of my management systems, but I don't understand it, so I would like to ask how to connect our project with the front end?
