### ISSUE TITLE
Request to update instructions for Windows

### ISSUE THREAD

**Issue by ishaan95** [grepthat/libOpenDRIVE#73]
I noticed that build instructions for Windows weren't exactly what was written in the README. If this could be added to the README, that'd be great. 

Assuming that Visual Studio with Windows SDK 10.x along with cmake has been installed already, here are the commands:

> mkdir build && cd build
> cmake --build build --target ALL_BUILD --config Release

The `test-xodr.exe` executable file will be in the Build/Release directory.

**Comment by grepthat** [comment]
Thanks for the info! What do you mean by "weren't exactly what was written"? Does using `cmake ..` give you an error?
