### ISSUE TITLE
any plan on junction element?

### ISSUE THREAD

**Issue by yonhdee** [grepthat/libOpenDRIVE#8]
i'm wondering about routing(path planning) on .xodr, which may require a node-edge based data structure, is there any plan or roadmap on implementing more OpenDrive features?
ps. libOpenDRIVE is a great project

**Comment by grepthat** [comment]
Appreciate it! What kind of API are you looking for with routing? I could add that next. Otherwise I'm currently finishing road objects and had planned on doing road signals next.

**Comment by yonhdee** [comment]
it's like when you're using google map, you request to go from current location(road_id, s, l) to destination(road_id, s, l), then routing module responds with a route(node-edge-node-edge......edge-node)
i noticed there's no related design in opendrive docs, and most users need to implement routing-graph themselves
and i'll do some further study on this

**Comment by Rogers0701** [comment]
>

what kind of planning algorithm?A-star or Dijkstra？

**Comment by yonhdee** [comment]
> 

astar might not function well in road_network due to difficulty in heuristic calculation, lanelet2_routing uses Dijkstra to search in lanelet IDs which runs fast

**Comment by grepthat** [comment]
The lib is now parsing junction elements and lane predecessor/successors. It's now possible to get a routing graph via `OpenDriveMap:: get_routing_graph()` and a shortest path via `RoutingGraph::shortest_path(const LaneKey& from, const LaneKey& to)`. The shortest path is currently calculated via Dijkstra algorithm. Feel free to contribute more sophisticated path-finding algorithms.

The routing functionality is also added to https://odrviewer.io - by highlighting predecessor/successors lanes and being able to run a shortest path search.
