### ISSUE TITLE
How to get the successors for the specific lane?

### ISSUE THREAD

**Issue by jeonghyunjo** [grepthat/libOpenDRIVE#85]
Hi developers. I really appreciate to the great work!
I like to know how to get the successors of the specific lane, but it seems it only works by using routinggraph.
What I want to do is getting successors from OpenDriveMap object. Is there already implemented function?

Thank you

**Comment by grepthat** [comment]
Best is to use the routing graph, it also has the function `get_lane_successors`. Here is an example:
```c++
odr::LaneKey lane("508", 0.0, -1);
std::vector<odr::LaneKey> lane_successors = odr_map.get_routing_graph().get_lane_successors(lane);
for (const odr::LaneKey& succ : lane_successors)
    printf("successor-lane: road '%s', lanesection %f, lane %d\n", succ.road_id.c_str(), succ.lanesection_s0, succ.lane_id);
```

There is also the attribute `odr::Lane::successor` but that only tells you successor **lane id**. You would then have to find out what the successor road is and find your successor lane in there. That is basically what `OpenDriveMap::get_routing_graph` already does.

**Comment by grepthat** [comment]
Does this answer your question?

**Comment by jeonghyunjo** [comment]
Thank you for your answer! I will take a look and will ask further questions.
