### ISSUE TITLE
parampoly3 parameters

### ISSUE THREAD

**Issue by YChen-1998** [grepthat/libOpenDRIVE#9]
Thank you. I appreciate it. I'd like to know how you calculated the equation for finding parampoly3 parameters at known control points. Thank you very much~

**Comment by grepthat** [comment]
check out this issue: https://github.com/grepthat/libOpenDRIVE/issues/7

**Comment by YChen-1998** [comment]
> check out this issue: #7
yes,I want to know how to get these four formulas.thank you very much
p0 = (aU | aV)
p1 = (bu/3 + p0x | bV/3 + p0y)
p2 = (cU/3 + 2*p1x - p0x  | cV/3 + 2*p1y - p0y)
p3 = (dU + 3*p2x - 3*p1x + p0x | dV + 3*p2y - 3*p1y + p0y)
